version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8-node

    steps:
      - checkout
      - node/install-packages:
          override-ci-command: make install

      - run:
          name: Build
          command: make build

      - run:
          name: Run Tests
          command: make test

      - run:
          name: Run Lints
          command: make lint

      - run:
          name: Build docs
          command: SITE_PREFIX=/0/artifacts/docs make docs

      - run:
          name: Preparing artifacts
          command: make artifact

      - store_artifacts:
          path: ./artifacts

workflows:
  build-and-test:
    jobs:
      - build-and-test
