version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: make build
            - run: make test
            - run: make lint
      - run:
          name: Preparing artifacts
          command: make artifact
      - store_artifacts:
          path: ./artifacts
workflows:
  build-and-test:
    jobs:
      - build-and-test
